# Discovery of brown dwarfs mining the 2MASS and SDSS databases

F. Jiménez-Esteban¹, K. A. Lutz², E. Solano¹

1. Spanish Virtual Observatory
2. Université de Strasbourg, CNRS, Observatoire Astronomique de Strasbourg, UMR 7550, F-67000, Strasbourg, France

This tutorial is based on the EURO-VO tutorial of the same name: http://www.euro-vo.org/sites/default/files/documents/tutorial-brown-dwarfs_2019Apr.pdf .

***

## Introduction 

Brown dwarfs are objects occupying the gap between the least massive stars and the most massive planets. They are intrinsically faint objects. Hence, heir detection is not straightforward and, in fact, was almost impossible until the advent of global surveys at deep optical and near-infrared bands like SDSS, 2MASS or DENIS. We propose here to mine the 2MASS point source catalogue (2MASS-PSC) and SDSS-DR9 databases to identify T-type brown dwarfs through an appropriate combination of colors in the optical and the infrared, an approach that perfectly fits into the Virtual Observatory.

In this use case, we explore different ways to do the same tasks with different VO tools. These tasks
include:
 1. obtaining data from the SDSS and 2MASS catalogues in a given sky region,
 2. crossmatching the results of these searches,
 3. filtering the resulting table for brown dwarfs, and
 4. verifying our sample of brown dwarfs.

Software packages needed for this tutorial are Aladin, TOPCAT, STILTS and Python (or you may just use the Binder in your web browser).

In [1]:
# Standard Library
from pathlib import Path

# Astronomy tools
from astropy import units as u
from astropy.coordinates import SkyCoord

# Access astronomical databases
import pyvo
from astroquery.simbad import Simbad
from astroquery.vizier import Vizier
from astroquery.xmatch import XMatch

# Sky visualization
from ipyaladin import Aladin

## Step #1: Discovery

[![Vizier](https://custom-icon-badges.demolab.com/badge/Vizier-gray.svg?logo=vizier&logoColor=orange&logoWidth=20)](https://vizier.cds.unistra.fr/viz-bin/VizieR "https://vizier.cds.unistra.fr/viz-bin/VizieR")

We start by searching for the 2MASS point source catalogue (2MASS-PSC) and the SDSS data release 9 catalogue (SDSS DR9). To find and query catalogues, there are two packages we can use: pyVO and astroquery. We will show pyVO for searching the 2MASS-PSC and astroquery for SDSS DR9. 

With the pyVo package we are using the TAP service of VizieR. TAP is a Virtual Observatory protocol to query databases of tables. The language we use to compile the query is called ADQL and is similar to SQL. For more details on ADQL see also the dedicated VO tutorial (http://docs.g-vo.org/adql-gaia/html/). 

In [2]:
tap_vizier = pyvo.dal.TAPService("https://tapvizier.cds.unistra.fr/TAPVizieR/tap")

query = """
SELECT  * 
FROM tables
WHERE description LIKE '%2MASS%Cutri%'
"""

mass_psc_set = tap_vizier.search(query).to_table()
mass_psc_set["table_name", "description"]

<Table length=13>
      table_name      ...
        object        ...
--------------------- ...
  J/ApJ/569/23/table1 ...
   J/ApJ/780/92/2mass ...
       II/281/2mass6x ...
 J/ApJ/564/421/table3 ...
           II/246/out ...
          VII/233/xsc ...
           II/241/out ...
  J/ApJ/569/23/table3 ...
  J/ApJ/569/23/table2 ...
   J/AJ/126/63/table1 ...
J/ApJS/190/100/table1 ...
 J/ApJ/564/421/table5 ...
 J/ApJ/564/421/table6 ...

As mentioned above we are interested in the 2MASS-pSC, which has the table_name `II/246/out` in VizieR. Before we move on to construct a more complicated query, we have a quick look at the 2MASS-PSC table and all the available columns. We do so by downloading the first 5 rows:

In [3]:
query = 'SELECT TOP 5 * FROM "II/246/out" '
mass_psc_head = tap_vizier.search(query).to_table()
mass_psc_head

<Table length=5>
 RAJ2000  DEJ2000   errMaj  errMin errPA ...  Nopt extKey scanKey coaddKey coadd
   deg      deg     arcsec  arcsec  deg  ...                                    
 float64  float64  float32 float32 int16 ... int16 int32   int32   int32   int16
--------- -------- ------- ------- ----- ... ----- ------ ------- -------- -----
44.996055 0.005565    0.17    0.16    76 ...     1     --   69347  1594959     9
45.004857 0.019806    0.06    0.06    90 ...     1     --   69347  1594959     9
45.004193 0.020956    0.06    0.06    90 ...     0     --   69347  1594959     9
44.995074 0.038204    0.38    0.31     0 ...     0     --   69347  1594959     9
44.963851 0.043587    0.22    0.17    95 ...     1     --   69347  1594959     9

As in the original tutorial, we only want to get data within a 14arcmin radius of RA=08h30m00s, Dec=01d30m00s. ADQL has a function, which allows to run an astronomical cone search query. From the quick inital inspection of the table we now know that we will need the columns `RAJ2000` and `DEJ2000` to only get sources at a certain location. Since we want to get colours for our Brown Dwarf candidates, we will also want to get the `Jmag`, `Hmag` and `Kmag` columns. For a different analysis you might want to choose other columns. 

In [4]:
coord = SkyCoord(ra="08:30:00", dec="01:30:00", unit=(u.hourangle, u.deg))

query = """
SELECT * 
FROM \"II/246/out\" as tm_psc 
WHERE 1=CONTAINS(POINT(\'ICRS\', tm_psc.RAJ2000, tm_psc.DEJ2000),
                 CIRCLE(\'ICRS\', {:.3f}, {:.3f}, 14/60))
""".format(
    coord.ra.value,
    coord.dec.value,
)

mass_psc = tap_vizier.search(query).to_table()
mass_psc

<Table length=683>
 RAJ2000   DEJ2000   errMaj  errMin errPA ... extKey scanKey coaddKey coadd
   deg       deg     arcsec  arcsec  deg  ...                              
 float64   float64  float32 float32 int16 ... int32   int32   int32   int16
---------- -------- ------- ------- ----- ... ------ ------- -------- -----
127.509154 1.269173     0.2    0.15    87 ...     --   43956  1010984   221
127.507779 1.272875    0.12    0.11    86 ...     --   43956  1010984   221
127.514167 1.277495    0.23    0.21    51 ...     --   43956  1010984   221
127.463251 1.271903    0.07    0.07     0 ...     --   43955  1010947    56
127.463023   1.2864    0.06    0.06     0 ...     --   43955  1010947    56
 127.48465 1.271192    0.06    0.06     0 ...     --   43955  1010947    56
127.485565 1.275456     0.2    0.17     4 ...     --   43955  1010947    56
127.494339 1.280734    0.15    0.15   145 ...     --   43955  1010947    56
127.494645 1.296204    0.07    0.07    17 ...     --   43955  1010947    56
       ...      ...     ...     ...   ... ...    ...     ...      ...   ...
127.471749 1.699981    0.15    0.15   145 ...     --   43955  1010949    80
127.485472 1.701631    0.07    0.07    17 ...     --   43955  1010949    80
 127.50233 1.707568    0.06    0.06    90 ...     --   43956  1010982   198
127.469423  1.71372    0.12    0.11   101 ...     --   43955  1010949    80
127.451948 1.721205    0.06    0.06     0 ...     --   43955  1010949    80
127.395474  1.69711    0.34    0.32    88 ...     --   43955  1010949    80
127.432292 1.717116    0.07    0.06    96 ...     --   43955  1010949    80
127.433857 1.723263    0.07    0.07    17 ...     --   43955  1010949    80
127.531902 1.729757    0.06    0.06    90 ...     --   43956  1010982   198
 127.53577 1.730293    0.37    0.35    45 ...     --   43956  1010982   198

Now that we have all the data we want from the 2MASS-PSC, we move on to query SDSS DR9 with astroquery. First we want to find out which tables are available:

In [6]:
catalog_list_sdss = Vizier.find_catalogs("SDSS DR9")
for catalog_ID, catalog in catalog_list_sdss.items():
    print(catalog_ID, ": ", catalog.description)

V/139 :  The SDSS Photometric Catalog, Release 9 (Adelman-McCarthy+, 2012)
J/A+A/547/L1 :  SDSS-III DR9 DLA catalogue (Noterdaeme+, 2012)
J/A+A/598/A92 :  New ultracool subdwarfs (Lodieu+, 2017)
J/A+A/616/A97 :  SDSS QSO DR7 and DR9 (D'Isanto+, 2018)
J/MNRAS/444/2456 :  Spectral galaxy pairs from SDSS DR9 (Yang+, 2014)
J/MNRAS/445/1331 :  White-dwarf + main-sequence binaries in SDSS DR9 (Li+, 2014)
J/MNRAS/450/905 :  New SNe in SDSS DR9 (Graur+, 2015)
J/MNRAS/458/3808 :  DR9-12 SDSS WDMS binaries (Rebassa-Mansergas+, 2016)
J/other/NewA/58.61 :  SDSS DR9 galaxy clusters optical catalog (Banerjee+, 2018)
J/other/RAA/17.62 :  Candidate members of 4 stellar streams (Li+, 2017)


We want to get data from the catalogue called `V/139`. As before let's have a look at a few rows (per default `Vizier.get_catalogs` gives you 50 rows) of the code to figure out, which ones are most interesting for us.

In [7]:
test_sdss = Vizier.get_catalogs("V/139")
print(test_sdss)
test_sdss[0]

TableList with 1 tables:
	'0:V/139/sdss9' with 21 column(s) and 50 row(s) 


<Table length=50>
 mode q_mode   cl         SDSS9        ...  e_imag   zmag   e_zmag   zsp  
                                       ...   mag     mag     mag          
uint8  str1  uint8        str19        ... float32 float32 float32 float64
----- ------ ----- ------------------- ... ------- ------- ------- -------
    2            6 J025955.29+000252.0 ...   0.163  21.474   0.404      --
    2            3 J025956.07+000300.0 ...   0.119  21.032   0.430      --
    2            3 J025956.06+000259.9 ...   0.146  20.346   0.189      --
    2            3 J025956.06+000259.7 ...   0.084  20.942   0.310      --
    2            3 J025956.06+000259.9 ...   0.102  20.139   0.238      --
    2            3 J025956.06+000259.9 ...   0.119  20.811   0.229      --
    2            3 J025956.06+000259.9 ...   0.148  20.530   0.285      --
    2            3 J025956.06+000259.9 ...   0.091  21.022   0.241      --
    2            6 J025956.06+000300.0 ...   0.120  20.665   0.249      --
  ...    ...   ...                 ... ...     ...     ...     ...     ...
    2            3 J025953.59+000242.0 ...   0.145  20.721   0.197      --
    2            3 J025953.59+000241.9 ...   0.104  21.093   0.306      --
    2            3 J025953.60+000242.0 ...   0.135  21.110   0.331      --
    2            3 J025953.59+000241.9 ...   0.108  21.248   0.493      --
    2            3 J025953.59+000241.9 ...   0.136  21.443   0.637      --
    2            3 J025953.58+000241.8 ...   0.121  22.125   0.781      --
    1      +     3 J025953.58+000241.9 ...   0.112  21.892   0.522      --
    2            3 J025953.58+000241.9 ...   0.138  21.315   0.452      --
    2            3 J025953.58+000241.9 ...   0.100  21.122   0.373      --
    2            3 J025952.90+000248.4 ...   0.444  21.606   0.667      --

Again we want to get the coordinates of the source as well as magnitudes at all five SDSS bands (u, g, r, i  and z), and a classification (cl). Do restrict the query to returning these columns and to get more than 50 rows returned, we create a custom `Vizier` object and then use this object to again query within 14arcmin of RA=08h30m00s, Dec=01d30m00s.

In [8]:
custom_vizier = Vizier(
    row_limit=-1,
    columns=["RA_ICRS", "DE_ICRS", "umag", "gmag", "rmag", "imag", "zmag", "cl"],
)
coord = SkyCoord(ra="08:30:00", dec="01:30:00", unit=(u.hourangle, u.deg))
sdss_results = custom_vizier.query_region(coord, radius=14 * u.arcmin, catalog="V/139")
sdss_results

TableList with 1 tables:
	'0:V/139/sdss9' with 8 column(s) and 12405 row(s) 

So we have one table in the resulting lists of tables. It is called `V/139/sdss9`. Let's have a look at it:

In [9]:
sdss_results[0]

<Table length=12405>
 RA_ICRS    DE_ICRS     umag    gmag    rmag    imag    zmag    cl 
   deg        deg       mag     mag     mag     mag     mag        
 float64    float64   float32 float32 float32 float32 float32 uint8
---------- ---------- ------- ------- ------- ------- ------- -----
127.267366   1.512930  21.853  19.732  18.870  18.564  18.379     6
127.267372   1.512928  22.250  19.697  18.855  18.568  18.306     6
127.267372   1.512928  22.047  19.751  18.879  18.549  18.383     6
127.267727   1.495873  22.879  22.223  21.492  21.122  20.872     3
127.267754   1.495933  22.972  22.431  21.465  21.162  21.009     3
127.267831   1.500005  23.816  24.462  22.470  20.754  20.033     6
127.267836   1.495947  22.638  22.051  21.045  20.627  20.785     3
127.267853   1.499961  24.527  24.690  22.381  20.670  20.016     6
127.267955   1.499932  24.332  24.996  23.056  20.649  19.976     6
       ...        ...     ...     ...     ...     ...     ...   ...
127.721086   1.454952  25.206  22.518  21.180  20.003  19.220     6
127.721092   1.454942  24.141  22.402  21.299  19.986  19.388     6
127.721106   1.454915  25.321  22.688  21.179  20.001  19.185     6
127.721135   1.433421  24.965  23.102  21.848  21.408  20.790     6
127.721294   1.428704  23.008  22.731  22.155  21.610  22.793     3
127.721770   1.431717  24.914  22.575  21.113  20.438  20.019     6
127.721857   1.451469  22.933  22.365  21.472  21.923  20.895     3
127.722534   1.455524  23.442  23.378  22.518  22.918  21.866     3
127.722635   1.433612  24.813  23.994  22.453  21.173  20.798     3
127.722672   1.455765  22.961  25.752  22.950  22.003  23.070     6

## Step #2: Cross-matching


[![Xmatch](https://custom-icon-badges.demolab.com/badge/Xmatch-gray.svg?logo=xmatch&logoColor=blue&logoWidth=20)](http://cdsxmatch.u-strasbg.fr/ "http://cdsxmatch.u-strasbg.fr/")

In this next step, we find common sources in the 2MASS-PSC and SDSS-DR9 catalogues. One simple way to do this using the CDS XMatch service, which can also be reached with `astroquery`. The most reliable way to quuery XMatch is by uploading one of the tables (which will also make sure we stay in our region of interest) and crossmatching it to a table available in VizieR. 

In [10]:
mass_psc.write("Data/2MASS_PSC.vot", format="votable", overwrite=True)
sdss_results[0].write("Data/SDSS_DR9.vot", format="votable", overwrite=True)

In [11]:
sdss_mass = XMatch.query(
    cat1=Path("Data/2MASS_PSC.vot").open(),
    cat2="vizier:V/139/sdss9",
    max_distance=4 * u.arcsec,
    colRA1="RAJ2000",
    colDec1="DEJ2000",
)
sdss_mass

<Table length=717>
angDist   RAJ2000   DEJ2000   errMaj  errMin ... f_zsp spType  spCl subClass
float64   float64   float64  float64 float64 ... int64 int64  int64  int64  
-------- ---------- -------- ------- ------- ... ----- ------ ----- --------
0.352101 127.509154 1.269173     0.2    0.15 ...    --     --    --       --
0.152435 127.507779 1.272875    0.12    0.11 ...    --     --    --       --
0.217574 127.514167 1.277495    0.23    0.21 ...    --     --    --       --
0.048922 127.463251 1.271903    0.07    0.07 ...    --     --    --       --
0.023156 127.463023   1.2864    0.06    0.06 ...    --     --    --       --
0.102852  127.48465 1.271192    0.06    0.06 ...    --     --    --       --
0.385255 127.485565 1.275456     0.2    0.17 ...    --     --    --       --
 0.18744 127.494339 1.280734    0.15    0.15 ...    --     --    --       --
0.038231 127.494645 1.296204    0.07    0.07 ...    --     --    --       --
0.125123 127.483247 1.302628    0.06    0.06 ...    --     --    --       --
     ...        ...      ...     ...     ... ...   ...    ...   ...      ...
0.231895 127.471749 1.699981    0.15    0.15 ...    --     --    --       --
0.108018 127.485472 1.701631    0.07    0.07 ...    --     --    --       --
0.033205  127.50233 1.707568    0.06    0.06 ...    --     --    --       --
0.127126 127.469423  1.71372    0.12    0.11 ...    --     --    --       --
0.029366 127.451948 1.721205    0.06    0.06 ...    --     --    --       --
0.475815 127.395474  1.69711    0.34    0.32 ...    --     --    --       --
0.063468 127.432292 1.717116    0.07    0.06 ...    --     --    --       --
0.078846 127.433857 1.723263    0.07    0.07 ...    --     --    --       --
0.036173 127.531902 1.729757    0.06    0.06 ...    --     --    --       --
0.676936  127.53577 1.730293    0.37    0.35 ...    --     --    --       --

For the SDSS DR9 table this action has given us all the columns. So before we move on, we restrict the table to the columns, we are actually interested in. 

In [12]:
sdss_mass = sdss_mass[
    "2MASS",
    "RAJ2000",
    "DEJ2000",
    "Jmag",
    "Hmag",
    "Kmag",
    "SDSS9",
    "RAdeg",
    "DEdeg",
    "umag",
    "gmag",
    "rmag",
    "imag",
    "zmag",
    "cl",
]

print(f"We are currently working with {len(sdss_mass)} sources")

We are currently working with 717 sources


## Step #3: Filtering
In this step we select all those sources from our cross-matched catalogue that have colours and fluxes as expected for brown dwarfs. 

The selection cirteria for Brown Dwarfs are:
 - `umag > 22.0` --> magnitude in u-band fainter than 22.0mag
 - `gmag > 22.2` --> magnitude in g-band fainter than 22.2mag
 - `Jmag - Hmag < 0.3` --> J-H band colour smaller than 0.3mag
 - `Hmag - Kmag < 0.3` --> H-K band colour smaller than 0.3mag

We now apply these selection criteria to our table of point sources. 

In [13]:
# Add columsn with J-H and H-K colour
sdss_mass["J-H"] = sdss_mass["Jmag"] - sdss_mass["Hmag"]
sdss_mass["H-K"] = sdss_mass["Hmag"] - sdss_mass["Kmag"]
# Limit sources to those that fulfil the selection criteria
index_bd = (
    (sdss_mass["umag"] > 22.0)
    & (sdss_mass["gmag"] > 22.2)
    & (sdss_mass["J-H"] < 0.3)
    & (sdss_mass["H-K"] < 0.3)
)
candidates = sdss_mass[index_bd]
print(f"We have {len(candidates)} candidates for Brown Dwarfs")

We have 2 candidates for Brown Dwarfs


In [14]:
candidates

<Table length=2>
     2MASS        RAJ2000   ...         J-H                 H-K         
     str16        float64   ...       float64             float64       
---------------- ---------- ... ------------------- --------------------
08304878+0128311 127.703265 ...  0.1490000000000009 -0.21799999999999997
08304512+0134404 127.688007 ... 0.15899999999999892  0.25200000000000067

Note that we are using slightly different selection criteria here in the notebook than in the original tutorial. The reason is the following. The CDS XMatch service uses VizieR tables with their default filtering. For the SDSS DR 9 table, VizieR will filter to only use primary sources and disregard secondary sources, which is not the case when downloading the VizieR table with e.g. TOPCAT. Now the primary SDSS source for this brown dwarf is classified as an extended source by the automated SDSS pipeline, probably because it is hardly detected and very faint. So if we remove all extended sources we also throw away the target of our studies. Hence, the filtering in this notebook is less strict to allow 

## Step #4: Verification of the Brown Dwarf candidates

### Visualization

[![Aladin](https://custom-icon-badges.demolab.com/badge/Aladin-gray.svg?logo=aladin&logoColor=purple&logoWidth=20)](https://aladin.cds.unistra.fr/aladin.gml "https://aladin.cds.unistra.fr/aladin.gml")

The ipyaladin package allows to run an instance of Aladin Lite in your Jupyter notebook. 

In [15]:
aladin1 = Aladin(
    survey="P/SDSS9/color",
    fov=0.03,
    target="{:.4f} {:.4f}".format(candidates["RAJ2000"][0], candidates["DEJ2000"][0]),
)
aladin1

Aladin(fov=0.03, options=['allow_full_zoomout', 'coo_frame', 'fov', 'full_screen', 'log', 'overlay_survey', 'o…

As with any instance of Aladin Lite you can zoom in and out by scrolling your mouse. In the top left corner of the widget, you may chose which survey to look at, add layers, search for sources, ... 

You can also add tables to the widget by:

In [16]:
aladin1.add_table(candidates)

If you now click on the small square indicating the location of the source, the widget will show the corresponding table values in the lower part of the widget. 

As you can see at one of the locations hardly anything is visible and at the location of the other brown dwarf candidate, there is a bright star. To further investigate these two sources, we now query Simbad for them. 

### Check in Simbad

[![Simbad](https://custom-icon-badges.demolab.com/badge/Simbad-gray.svg?logo=simbad&logoColor=lightblue&logoWidth=20)](https://simbad.u-strasbg.fr/simbad/ "https://simbad.u-strasbg.fr/simbad/")

In the Simbad database, an object type is assigned to every entry. So if this Brown Dwarf candidate is in the Simbad database, we might learn more about the object type:

In [17]:
# First candidate has an index 0
customSimbad = Simbad()
customSimbad.remove_votable_fields("coordinates")
customSimbad.add_votable_fields(
    "ra(2;A;ICRS;J2000;2000)",
    "dec(2;D;ICRS;J2000;2000)",
    "otype",
)
candidate_coord = SkyCoord(
    ra=candidates["RAJ2000"][0],
    dec=candidates["DEJ2000"][0],
    unit=u.deg,
)
candidate_simbad = customSimbad.query_region(candidate_coord, radius=10 * u.arcsec)
candidate_simbad

<Table length=1>
        MAIN_ID         RA_2_A_ICRS_J2000_2000 ...  OTYPE  SCRIPT_NUMBER_ID
                               "h:m:s"         ...                         
         object                 str13          ...  object      int32      
----------------------- ---------------------- ... ------- ----------------
2MASS J08304878+0128311          08 30 48.7836 ... BrownD*                1

In [18]:
# First candidate has an index 1
customSimbad = Simbad()
customSimbad.remove_votable_fields("coordinates")
customSimbad.add_votable_fields(
    "ra(2;A;ICRS;J2000;2000)",
    "dec(2;D;ICRS;J2000;2000)",
    "otype",
)
candidate_coord = SkyCoord(
    ra=candidates["RAJ2000"][1],
    dec=candidates["DEJ2000"][1],
    unit=u.deg,
)
candidate_simbad = customSimbad.query_region(candidate_coord, radius=1 * u.arcmin)
candidate_simbad

/home/manon.marchand/miniconda3/envs/cds-tutos/lib/python3.10/site-packages/astroquery/simbad/core.py:135: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '8:30:45.12168 +1:34:40.4436': No astronomical object found :
  warnings.warn("Warning: The script line number %i raised "


Indeed the first candidate is classified as a brown dwarf. Within 10arcsec of the second source, no entry is found in Simbad although this is the brighter star. The reason for this might be the following: sources in Simbad are sources that have individually been discussed in the literature. If no papers have been published specifcially about this object, it will not appear in Simbad. However, as the object was included in the SDSS tables it is included in VizieR through the table it belongs to. 

If we now want to see, in which papers the Brown Dwarf 2MASS J08304878+0128311 was included, we may use the following query in Simbad.

In [19]:
tap_simbad = pyvo.dal.TAPService("https://simbad.cds.unistra.fr/simbad/sim-tap")

query = """
SELECT BIBCode, Journal, Title, "year", Volume,
       Page || '-' || Last_Page AS "Pages", DOI 
FROM ref JOIN has_ref ON oidbibref = oidbib 
         JOIN ident ON has_ref.oidref = ident.oidref 
WHERE id = '2MASS J08304878+0128311'
ORDER BY "year" DESC; 
"""

result = tap_simbad.search(query).to_table()
result

<Table length=20>
      bibcode       journal ...   Pages                 doi               
       object        object ...   object               object             
------------------- ------- ... --------- --------------------------------
2020AJ....159..257B      AJ ...   257-257         10.3847/1538-3881/ab84f4
2016ApJ...827...25B     ApJ ...     25-25       10.3847/0004-637X/827/1/25
2016A&A...589A..49S     A&A ...     49-49      10.1051/0004-6361/201527359
2016ApJ...817..112S     ApJ ...                10.3847/0004-637X/817/2/112
2015ApJ...810..158F     ApJ ...                10.1088/0004-637X/810/2/158
2014ApJ...793...75R     ApJ ...                 10.1088/0004-637X/793/2/75
2013MNRAS.433.2054S   MNRAS ... 2054-2063             10.1093/mnras/stt876
2013MNRAS.433..457B   MNRAS ...   457-497             10.1093/mnras/stt740
2012ApJ...752...56F     ApJ ...                 10.1088/0004-637X/752/1/56
2012ApJ...748...74L     ApJ ...                 10.1088/0004-637X/748/2/74
2012ApJ...757..110B     ApJ ...                10.1088/0004-637X/757/2/110
2011ApJS..197...19K    ApJS ...                 10.1088/0067-0049/197/2/19
2010A&A...515A..92S     A&A ...     92-92      10.1051/0004-6361/201014264
2010ApJ...710.1142B     ApJ ... 1142-1169     10.1088/0004-637X/710/2/1142
2009yCat....1.2023S    yCat ...                                           
2009AJ....137....1F      AJ ...      1-18        10.1088/0004-6256/137/1/1
2008ApJ...676.1281M     ApJ ... 1281-1306                   10.1086/524721
2008MNRAS.390.1517C   MNRAS ... 1517-1526 10.1111/j.1365-2966.2008.13855.x
2006ApJ...637.1067B     ApJ ... 1067-1093                   10.1086/498563
2004AJ....127.3553K      AJ ... 3553-3578                   10.1086/420707

For further reading you could now go to [ADS](https://ui.adsabs.harvard.edu/ "https://ui.adsabs.harvard.edu/") and search for the publications via their bibcode (enter in the search field `bibcode:...`) or their doi (`doi:...`).

To design similar queries for your own research, have a look at [Simbad database schema](https://simbad.cds.unistra.fr/simbad/tap/tapsearch.html "https://simbad.cds.unistra.fr/simbad/tap/tapsearch.html").